# Generated by Django 5.0.7 on 2024-07-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='devtools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('type', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
    ]
