# Generated by Django 5.0.7 on 2024-07-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developtool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devtools',
            old_name='type',
            new_name='kind',
        ),
    ]
