# Generated by Django 5.0.7 on 2024-07-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='devtool',
            field=models.CharField(max_length=24, verbose_name='예상 개발툴'),
        ),
        migrations.AlterField(
            model_name='post',
            name='interest',
            field=models.IntegerField(default=0, verbose_name='아이디어 관심도'),
        ),
    ]
