# Generated by Django 5.0.7 on 2024-07-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='board/%Y%m%d')),
                ('content', models.TextField(max_length=200)),
                ('like', models.IntegerField()),
            ],
        ),
    ]
