# Generated by Django 5.0.7 on 2024-07-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_post_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
