# Generated by Django 5.0.7 on 2024-07-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='actors',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='director',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='running_time',
            field=models.IntegerField(default=0),
        ),
    ]
