# Generated by Django 5.0.7 on 2024-07-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_actors_review_content_review_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('액션', '액션'), ('코미디', '코미디'), ('드라마', '드라마'), ('공포', '공포'), ('SF', 'SF'), ('로맨스', '로맨스'), ('애니메이션', '애니메이션'), ('다큐멘터리', '다큐멘터리'), ('기타', '기타')], max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
